version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "$NGINX_PORT:80"
    restart: always
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/mime.types:/etc/nginx/mime.types:ro"
      - "$NGINX_PUBLIC_FOLDER:/var/www/public"
