version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "$NGINX_PORT:80"
    restart: always
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "$NGINX_PUBLIC_FOLDER:/var/www/public"
